spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/seomoim?zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: 1111
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
        show_sql: true

  #javaMailSenderBean
  mail:
    host: smtp.gmail.com
    port: 587
    username: seocoding1@gmail.com
    password: hzhebhfkjyvxwzqv
    properties:
      mail:
        smtp:
          auth: true
#          timeout: 5000
          starttls:
            enable: true
    default-encoding:

logging level:
  org.hibernate.sql: debug



#  기본 1800초 30분ㅂㅂ
server:
  servlet:
    session:
      timeout: 1800
#      개발시 사용하고 노출하지말자
  error:
    include-exception: true

mail:
  address:
    admin: admin@gmail.com




