spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/seomoim
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
        show_sql: true

logging level:
  org.hibernate.sql: debug




